# Person is diabetic or not.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
# Loading the diabetes dataset to a pandas dataframe
diabetes_dataset = pd.read_csv("data/diabetes_dataset_800_records.csv")

In [3]:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diabetic
0,3,76,75,22,129,22.5,0.328,68,0
1,17,92,94,9,30,21.0,0.643,59,1
2,0,120,109,33,127,32.4,0.753,76,1
3,0,110,94,28,157,23.0,2.396,42,0
4,3,93,88,13,198,45.1,1.541,72,1

In [5]:
diabetes_dataset.shape

(800, 9)

In [6]:
# getting statistical measures of data
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diabetic
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,8.370000,135.027500,75.673750,33.763750,159.473750,33.756875,1.267514,51.331250,0.880000
std,5.189823,38.062287,20.953845,15.448422,82.700762,9.174449,0.671466,16.785074,0.325165
min,0.000000,70.000000,40.000000,7.000000,15.000000,18.000000,0.080000,21.000000,0.000000
25%,4.000000,102.000000,57.000000,21.000000,85.750000,26.175000,0.693500,37.000000,1.000000
50%,8.000000,134.000000,76.500000,33.000000,164.000000,33.400000,1.239500,52.000000,1.000000
75%,13.000000,168.000000,94.000000,47.000000,229.250000,41.500000,1.812000,65.000000,1.000000
max,17.000000,200.000000,110.000000,60.000000,300.000000,50.000000,2.499000,80.000000,1.000000

In [8]:
diabetes_dataset['Diabetic'].value_counts()

Diabetic
1    704
0     96
Name: count, dtype: int64

In [10]:
diabetes_dataset.groupby('Diabetic').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Diabetic,,,,,,,,
0,4.708333,115.53125,76.427083,33.104167,114.718750,27.954167,1.316927,39.625000
1,8.869318,137.68608,75.571023,33.853693,165.576705,34.548153,1.260776,52.927557

In [11]:
# Separate the data and labels
X = diabetes_dataset.drop(columns = 'Diabetic', axis=1)
Y = diabetes_dataset['Diabetic']

In [12]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,3,76,75,22,129,22.5,0.328,68
1,17,92,94,9,30,21.0,0.643,59
2,0,120,109,33,127,32.4,0.753,76
3,0,110,94,28,157,23.0,2.396,42
4,3,93,88,13,198,45.1,1.541,72

In [13]:
Y.head()

0    0
1    1
2    1
3    0
4    1
Name: Diabetic, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, stratify=Y, random_state=42)

In [17]:
print(X.shape, X_train.shape, X_test.shape)

(800, 8) (560, 8) (240, 8)

In [18]:
# Training the Model

In [19]:
classifier = svm.SVC(kernel='linear')

In [21]:
# Training the Support Vector Machine Classifier
classifier.fit(X_train, y_train)

SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [25]:
X_train_pred = classifier.predict(X_train)
training_data_acc = accuracy_score(X_train_pred, y_train)

In [26]:
print("Accuracy Score of the Training Data :", training_data_acc)

Accuracy Score of the Training Data : 0.9232142857142858

In [27]:
# Accuracy score on the test data
X_test_pred = classifier.predict(X_test)
test_data_acc = accuracy_score(X_test_pred, y_test)

In [28]:
print("Accuracy Score of the Training Data :", test_data_acc)

Accuracy Score of the Training Data : 0.9291666666666667

##### Making a Predictive System

In [29]:
input_data = (5,166,72,19,175,25.8,0.587,51)

#1->85->66->->29->0->26.6->0.351->31--> for not diabetic

# Changing the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

input_data_reshaped

array([[  5.   , 166.   ,  72.   ,  19.   , 175.   ,  25.8  ,   0.587,
         51.   ]])

In [36]:
prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
    print('The person is not diabetic')
else:
    print('The person is diabetic')

[1]
The person is diabetic

C:\Users\userh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [49]:
input_data1 = (1,85,66,29,0,26.6,0.351,31)

#1->85->66->->29->0->26.6->0.351->31--> for not diabetic

# Changing the input data to numpy array
input_data_as_numpy_array1 = np.asarray(input_data1)

#reshape the array as we are predicting for one instance
input_data_reshaped1 = input_data_as_numpy_array1.reshape(1,-1)

input_data_reshaped

array([[  5.   , 166.   ,  72.   ,  19.   , 175.   ,  25.8  ,   0.587,
         51.   ]])

In [50]:
prediction = classifier.predict(input_data_reshaped1)
print(prediction)

if (prediction[0] == 0):
    print('The person is not diabetic')
else:
    print('The person is diabetic')

[0]
The person is not diabetic

C:\Users\userh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

##### Saving the trained model

In [51]:
import pickle

In [52]:
filename = 'model/trained_model.sav'
pickle.dump(classifier, open(filename,'wb'))

In [53]:
# Pickle.dump(classifier, open('filename', 'wb')): This line uses the pickle.dump and save the 
# trained machine learning model (classifier) to a file.
# the file is opened in binary write mode ('wb'). This process is often referred to as 'pickling' the model.

# filename = ('trained_model.sav' : This line defines the filename for the saved model.
# The choice of the '.sav' extension is common but not mandatory.
# The extension is often used to indicate that the file contains serialized or saved data.

In [54]:
# Loading the saved model
loaded_model = pickle.load(open('model/trained_model.sav','rb'))

In [55]:
# open('trained_model.sav','rb'): opens the file 'trained_model.sav' in binary read mode.
# the rb mode is used for reading binary files.

In [56]:
input_data2 = (6,148,72,35,0,33.6,0.627,50)

# changing the input_data to numpy_array
input_data_as_numpy_array2 = np.asarray(input_data2)

#reshape the array as we are predicting for one instance
input_data_reshaped2 = input_data_as_numpy_array2.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped2)
print(prediction)

if (prediction[0] == 0):
    print('The person is not diabetic')
else:
    print('The person is diabetic')

[1]
The person is diabetic

C:\Users\userh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [57]:
input_data3 = (1,85,66,29,0,26.6,0.351,31)

# changing the input_data to numpy_array
input_data_as_numpy_array3 = np.asarray(input_data3)

#reshape the array as we are predicting for one instance
input_data_reshaped3 = input_data_as_numpy_array3.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped3)
print(prediction)

if (prediction[0] == 0):
    print('The person is not diabetic')
else:
    print('The person is diabetic')

[0]
The person is not diabetic

C:\Users\userh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(